
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label1;

	private global::Gtk.Entry DatabaseEntry;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label2;

	private global::Gtk.Entry UserNameEntry;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label3;

	private global::Gtk.Entry PasswordEntry;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label label5;

	private global::Gtk.ComboBox combobox1;

	private global::Gtk.Fixed fixed2;

	private global::Gtk.Entry SearchEntry;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label label4;

	private global::Gtk.ScrolledWindow TablesScroll;

	private global::Gtk.VBox TableBox;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button CheckAllButton;

	private global::Gtk.Button UnCheckAllButton;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Button CloseButton;

	private global::Gtk.Button TestConnectionButton;

	private global::Gtk.VSeparator vseparator1;

	private global::Gtk.Button GenerateButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Database Entities");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Modal = true;
		this.BorderWidth = ((uint)(10));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox = new global::Gtk.VBox();
		this.vbox.Name = "vbox";
		this.vbox.Spacing = 6;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.WidthRequest = 100;
		this.label1.Name = "label1";
		this.label1.Xalign = 0F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Databse Server");
		this.hbox2.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.DatabaseEntry = new global::Gtk.Entry();
		this.DatabaseEntry.CanFocus = true;
		this.DatabaseEntry.Name = "DatabaseEntry";
		this.DatabaseEntry.IsEditable = true;
		this.DatabaseEntry.InvisibleChar = '●';
		this.hbox2.Add(this.DatabaseEntry);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.DatabaseEntry]));
		w2.Position = 1;
		this.vbox.Add(this.hbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox[this.hbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.WidthRequest = 100;
		this.label2.Name = "label2";
		this.label2.Xalign = 0F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("User Name");
		this.hbox1.Add(this.label2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label2]));
		w4.Position = 0;
		w4.Expand = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.UserNameEntry = new global::Gtk.Entry();
		this.UserNameEntry.WidthRequest = 140;
		this.UserNameEntry.CanFocus = true;
		this.UserNameEntry.Name = "UserNameEntry";
		this.UserNameEntry.IsEditable = true;
		this.UserNameEntry.InvisibleChar = '●';
		this.hbox1.Add(this.UserNameEntry);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.UserNameEntry]));
		w5.Position = 1;
		this.vbox.Add(this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox[this.hbox1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.WidthRequest = 100;
		this.label3.Name = "label3";
		this.label3.Xalign = 0F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("User Password");
		this.hbox3.Add(this.label3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label3]));
		w7.Position = 0;
		w7.Expand = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.PasswordEntry = new global::Gtk.Entry();
		this.PasswordEntry.CanFocus = true;
		this.PasswordEntry.Name = "PasswordEntry";
		this.PasswordEntry.IsEditable = true;
		this.PasswordEntry.Visibility = false;
		this.PasswordEntry.InvisibleChar = '●';
		this.hbox3.Add(this.PasswordEntry);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.PasswordEntry]));
		w8.Position = 1;
		this.vbox.Add(this.hbox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox[this.hbox3]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.WidthRequest = 100;
		this.label5.Name = "label5";
		this.label5.Xalign = 0F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Database");
		this.hbox5.Add(this.label5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label5]));
		w10.Position = 0;
		w10.Expand = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.combobox1 = global::Gtk.ComboBox.NewText();
		this.combobox1.Name = "combobox1";
		this.hbox5.Add(this.combobox1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.combobox1]));
		w11.Position = 1;
		this.vbox.Add(this.hbox5);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox[this.hbox5]));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed();
		this.fixed2.HeightRequest = 20;
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.SearchEntry = new global::Gtk.Entry();
		this.SearchEntry.WidthRequest = 268;
		this.SearchEntry.CanFocus = true;
		this.SearchEntry.Name = "SearchEntry";
		this.SearchEntry.IsEditable = true;
		this.SearchEntry.HasFrame = false;
		this.SearchEntry.InvisibleChar = '●';
		this.fixed2.Add(this.SearchEntry);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.SearchEntry]));
		w13.X = 106;
		w13.Y = 10;
		this.vbox.Add(this.fixed2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox[this.fixed2]));
		w14.Position = 4;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.vbox.Add(this.fixed1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox[this.fixed1]));
		w15.Position = 5;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.WidthRequest = 100;
		this.label4.Name = "label4";
		this.label4.Xalign = 0F;
		this.label4.Yalign = 0.03F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Tables");
		this.hbox4.Add(this.label4);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label4]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.TablesScroll = new global::Gtk.ScrolledWindow();
		this.TablesScroll.HeightRequest = 200;
		this.TablesScroll.CanFocus = true;
		this.TablesScroll.Name = "TablesScroll";
		this.TablesScroll.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
		this.TablesScroll.HscrollbarPolicy = ((global::Gtk.PolicyType)(0));
		this.TablesScroll.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child TablesScroll.Gtk.Container+ContainerChild
		global::Gtk.Viewport w17 = new global::Gtk.Viewport();
		w17.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.TableBox = new global::Gtk.VBox();
		this.TableBox.Name = "TableBox";
		this.TableBox.Spacing = 6;
		w17.Add(this.TableBox);
		this.TablesScroll.Add(w17);
		this.hbox4.Add(this.TablesScroll);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.TablesScroll]));
		w20.Position = 1;
		this.vbox.Add(this.hbox4);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox[this.hbox4]));
		w21.Position = 6;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = -190;
		// Container child hbox7.Gtk.Box+BoxChild
		this.CheckAllButton = new global::Gtk.Button();
		this.CheckAllButton.WidthRequest = 80;
		this.CheckAllButton.CanFocus = true;
		this.CheckAllButton.Name = "CheckAllButton";
		this.CheckAllButton.UseUnderline = true;
		this.CheckAllButton.Label = global::Mono.Unix.Catalog.GetString("Check All");
		this.hbox7.Add(this.CheckAllButton);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.CheckAllButton]));
		w22.Position = 0;
		w22.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.UnCheckAllButton = new global::Gtk.Button();
		this.UnCheckAllButton.WidthRequest = 80;
		this.UnCheckAllButton.CanFocus = true;
		this.UnCheckAllButton.Name = "UnCheckAllButton";
		this.UnCheckAllButton.UseUnderline = true;
		this.UnCheckAllButton.Label = global::Mono.Unix.Catalog.GetString("Uncheck All");
		this.hbox7.Add(this.UnCheckAllButton);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.UnCheckAllButton]));
		w23.Position = 1;
		w23.Fill = false;
		this.vbox.Add(this.hbox7);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox[this.hbox7]));
		w24.Position = 7;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.vbox.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox[this.hseparator1]));
		w25.Position = 8;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.CloseButton = new global::Gtk.Button();
		this.CloseButton.WidthRequest = 80;
		this.CloseButton.CanFocus = true;
		this.CloseButton.Name = "CloseButton";
		this.CloseButton.UseUnderline = true;
		this.CloseButton.Label = global::Mono.Unix.Catalog.GetString("Close");
		this.hbox6.Add(this.CloseButton);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.CloseButton]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.TestConnectionButton = new global::Gtk.Button();
		this.TestConnectionButton.WidthRequest = 130;
		this.TestConnectionButton.CanFocus = true;
		this.TestConnectionButton.Name = "TestConnectionButton";
		this.TestConnectionButton.UseUnderline = true;
		this.TestConnectionButton.Label = global::Mono.Unix.Catalog.GetString("Test Connection");
		this.hbox6.Add(this.TestConnectionButton);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.TestConnectionButton]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator();
		this.vseparator1.Name = "vseparator1";
		this.hbox6.Add(this.vseparator1);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.vseparator1]));
		w28.Position = 2;
		w28.Padding = ((uint)(14));
		// Container child hbox6.Gtk.Box+BoxChild
		this.GenerateButton = new global::Gtk.Button();
		this.GenerateButton.WidthRequest = 130;
		this.GenerateButton.CanFocus = true;
		this.GenerateButton.Name = "GenerateButton";
		this.GenerateButton.UseUnderline = true;
		this.GenerateButton.Label = global::Mono.Unix.Catalog.GetString("Generate Entities");
		this.hbox6.Add(this.GenerateButton);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.GenerateButton]));
		w29.Position = 3;
		w29.Fill = false;
		this.vbox.Add(this.hbox6);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox[this.hbox6]));
		w30.Position = 9;
		w30.Expand = false;
		w30.Fill = false;
		this.Add(this.vbox);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 408;
		this.DefaultHeight = 514;
		this.Show();
		this.Hidden += new global::System.EventHandler(this.OnHidden);
		this.DatabaseEntry.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnDatabaseEntryKeyPressEvent);
		this.UserNameEntry.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnUserNameEntryKeyPressEvent);
		this.PasswordEntry.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnPasswordEntryKeyPressEvent);
		this.combobox1.Changed += new global::System.EventHandler(this.OnCombobox1Changed);
		this.SearchEntry.Changed += new global::System.EventHandler(this.OnSearchEntryChanged);
		this.CheckAllButton.Pressed += new global::System.EventHandler(this.OnCheckAllButtonPressed);
		this.UnCheckAllButton.Pressed += new global::System.EventHandler(this.OnUnCheckAllButtonPressed);
		this.CloseButton.Pressed += new global::System.EventHandler(this.OnCloseButtonPressed);
		this.TestConnectionButton.Pressed += new global::System.EventHandler(this.OnTestConnectionButtonPressed);
		this.GenerateButton.Pressed += new global::System.EventHandler(this.OnGenerateButtonPressed);
	}
}
